<?xml version="1.0" encoding="UTF-8"?>
<!-- Script de Ant del proyecto. NetBeans genera nbproject/build-impl.xml
     a partir de nbproject/project.xml y este archivo lo importa. -->
<project name="LibreriaOnline" default="default" basedir=".">
    <description>Builds, tests, and runs the project LibreriaOnline.</description>
    <import file="nbproject/build-impl.xml"/>
</project>
